language: go

go:
  - "1.14.12"

dist: xenial


notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
  - sudo apt-get update
  - pyenv versions
  - pyenv global 3.7.1
  - nvm install 14
  - npm install -g npm@6.x
  #- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $my_key -iv $my_iv -in myservice.env.enc -out myservice.env -d || true'

install:
- curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - make travis-ci

# To enable semantic-release, uncomment these sections.
before_deploy:
- pip install --user bump2version
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github

deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    branch: main
