language: go

go:
  - "1.18.x"
  - "1.19.x"
  - "1.20.x"

dist: xenial

notifications:
  email: true

before_install:
  - sudo apt-get update
  - pyenv versions
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.51.2

install:
- provider script
  script:
  - make travis-ci

# To enable semantic-release, uncomment these sections.
before_deploy:
- pip install --user bump2version

deploy:
- provider: script
  script:
    # Use nvm to install and use the Node LTS version (nvm is installed on all Travis images)
    - nvm install lts/*
    - npx semantic-release
  skip_cleanup: true
  on:
    branch: main
