language: go

go:
  - "1.18.x"
  - "1.19.x"
  - "1.20.x"

dist: jammy

notifications:
  email: true

before_install:
  - sudo apt-get update
  - pyenv versions

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.60.2

script:
  - make travis-ci

# To enable semantic-release, uncomment these sections
before_deploy:
  - pip install --user bump2version
  - nvm install lts/*
  - npm install @semantic-release/changelog
  - npm install @semantic-release/exec
  - npm install @semantic-release/git
  - npm install @semantic-release/github

deploy:
- provider: script
  script:
    - npx semantic-release
  skip_cleanup: true
  on:
    branch: main
    # only on 1 matrix job
    condition: $TRAVIS_GO_VERSION =~ ^1\.20
# ensure semantic-release is functional
- provider: script
  script:
    - npx semantic-release --dry-run
  skip_cleanup: true
  on:
    all_branches: true
    # only on 1 matrix job
    condition: $TRAVIS_GO_VERSION =~ ^1\.20
