language: go

env:
  - GO_VERSION="module" # The oldest version we claim to support
  - GO_VERSION="1.21.x" # The oldest version that enforces the minimum version of imported modules
  - GO_VERSION="stable" # The latest version

dist: jammy

notifications:
  email: true

before_install:
  - sudo apt-get update
  - pyenv versions

install:
  # Travis's docs claim to use gimme to install the go version but they in fact use go install. This does not support
  # the 1.18.x syntax or any equivalent. Travis's version of gimme is also unmaintained and broken. Use a maintained
  # version from the urfave org in its place.
  - curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/urfave/gimme/main/gimme
  - chmod +x ~/bin/gimme
  - gimme version
  - eval "$(gimme "$GO_VERSION")"
  - go env
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.60.2

script:
  - make travis-ci

# To enable semantic-release, uncomment these sections
before_deploy:
  - pip install --user bump2version
  - nvm install lts/*
  - npm install @semantic-release/changelog
  - npm install @semantic-release/exec
  - npm install @semantic-release/git
  - npm install @semantic-release/github

deploy:
- provider: script
  script:
    - npx semantic-release
  skip_cleanup: true
  on:
    branch: main
    # only on 1 matrix job
    condition: $TRAVIS_GO_VERSION =~ ^1\.21
# ensure semantic-release is functional
- provider: script
  script:
    - npx semantic-release --dry-run
  skip_cleanup: true
  on:
    all_branches: true
    # only on 1 matrix job
    condition: $TRAVIS_GO_VERSION =~ ^1\.21
